# configuration file for obj_detection  
  
  #object codes
  ERROR: -1
  BOTTLE: 0
  CAN: 1

  #calibration parameters for cans and bottles
  calibration_diameter_min: 10
  calibration_diameter_max: 20
  can_diameter_min: 35
  can_diameter_max: 40
  bottle_diameter_min: 25
  bottle_diameter_max: 29
